version: "3.8"

services:
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./data/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./data/sites/:/etc/nginx/conf.d/"
      - "./data/html/:/var/www/html/"
      - "./data/certs/:/etc/certs/"
